---
abstract: 'A Rinci transaction manager'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::chdir: 0
  Module::Build: 0.3601
  Perinci::Access::InProcess: 0.32
  Perinci::Examples: 0
  Test::More: 0.96
  UUID::Random: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Tx-Manager
requires:
  DBD::SQLite: 0
  DBI: 0
  File::Flock: 0
  File::Remove: 0
  JSON: 0
  Log::Any: 0
  Riap: v1.1.14
  Rinci: v1.1.27
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Perinci-Tx-Manager
  repository: http://github.com/sharyanto/perl-Perinci-Tx-Manager
version: 0.34
